/* contract.h - generated by viz/gen_contract_c.py. Palette index constants. */
#ifndef CONTRACT_H
#define CONTRACT_H
#define C_BLACK 0
#define C_WHITE 15
/* header band */
#define H_GREEN_DK 9
#define H_BLUE 10
#define H_CYAN 11
#define H_GREEN 12
#define H_RED 13
#define H_GOLD 14
/* wallet band */
#define W_BLUE 11
#define W_CYAN 12
/* mid band */
#define M_LED 11
#define M_RB0 8
#define M_RB_N 7
/* bottom band */
#define B_AMBER 11
#define B_VUG 12
#define B_VUY 13
#define B_VUR 14
#endif
