/* contract_cfg.h - generated by viz/gen_contract_c.py. CONFIG page ink
 * (uniform across all 16 zones; see spec.CFG_INK). */
#ifndef CONTRACT_CFG_H
#define CONTRACT_CFG_H
#define CF_BLACK 0
#define CF_BLUE 10
#define CF_CYAN 11
#define CF_GREEN 12
#define CF_RED 13
#define CF_AMBER 14
#define CF_WHITE 15
#endif
