#!/usr/bin/env python3
"""gen_contract_c.py - emit miner/contract.h (palette index constants) from spec.py."""
import spec as S

lines = [
    "/* contract.h - generated by viz/gen_contract_c.py. Palette index constants. */",
    "#ifndef CONTRACT_H", "#define CONTRACT_H",
    "#define C_BLACK 0", "#define C_WHITE 15",
    "/* header band */",
    "#define H_GREEN_DK 9", "#define H_BLUE 10", "#define H_CYAN 11", "#define H_GREEN 12",
    "#define H_RED 13", "#define H_GOLD 14",
    "/* wallet band */",
    "#define W_BLUE 11", "#define W_CYAN 12",
    "/* mid band */",
    "#define M_LED 11", "#define M_RB0 8", "#define M_RB_N 7",
    "/* bottom band */",
    "#define B_AMBER 11", "#define B_VUG 12", "#define B_VUY 13", "#define B_VUR 14",
    "#endif",
]
with open("../miner/contract.h", "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote miner/contract.h")

# ---- CONFIG page contract: UNIFORM ink in every zone (spec.CFG_INK) ----
_NAME = {0: "CF_BLACK", 10: "CF_BLUE", 11: "CF_CYAN", 12: "CF_GREEN",
         13: "CF_RED", 14: "CF_AMBER", 15: "CF_WHITE"}
cfg = ["/* contract_cfg.h - generated by viz/gen_contract_c.py. CONFIG page ink",
       " * (uniform across all 16 zones; see spec.CFG_INK). */",
       "#ifndef CONTRACT_CFG_H", "#define CONTRACT_CFG_H"]
for idx in sorted(S.CFG_INK):
    cfg.append("#define %s %d" % (_NAME.get(idx, "CF_%d" % idx), idx))
cfg.append("#endif")
with open("../miner/contract_cfg.h", "w") as f:
    f.write("\n".join(cfg) + "\n")
print("wrote miner/contract_cfg.h")
