#!/usr/bin/env python3
"""
gen_font_c.py - emit miner/font_gs.h from font4x6.py.

Run from viz/:  python3 gen_font_c.py
"""
import importlib


def emit_main():
    mod = importlib.import_module("font4x6")
    lo, hi = 32, 94
    gw, gh = mod.GW, mod.GH
    rows = []
    for code in range(lo, hi + 1):
        ch = chr(code)
        bmp = mod._F.get(ch) or mod._F.get(ch.upper()) or mod._F[' ']
        for r in range(gh):
            bits = sum(1 << (gw - 1 - c) for c in range(gw) if bmp[r][c] == '1')
            rows.append(bits)
    with open("../miner/font_gs.h", "w") as f:
        f.write("/* generated by viz/gen_font_c.py from font4x6 - do not edit */\n")
        f.write("#ifndef FONT_GS_H\n#define FONT_GS_H\n")
        f.write("#define FONT_LO %d\n#define FONT_HI %d\n" % (lo, hi))
        f.write("#define GLYPH_W %d\n#define GLYPH_H %d\n" % (gw, gh))
        f.write("static const unsigned char FONT[%d] = {\n" % len(rows))
        for i in range(0, len(rows), gh):
            f.write("    " + ",".join("0x%02x" % b for b in rows[i:i + gh]) + ",\n")
        f.write("};\n#endif\n")
    print("wrote miner/font_gs.h (%d glyphs, %dx%d)" % (hi - lo + 1, gw, gh))


def emit_wallet():
    """5x7 case-sensitive font for the WALLET field (legible mixed case, inset in well)."""
    mod = importlib.import_module("font5x7w")
    lo, hi = 32, 122                       # space..z (covers base58 + bech32)
    gw, gh = mod.GW, mod.GH
    rows = []
    for code in range(lo, hi + 1):
        ch = chr(code)
        bmp = mod._F.get(ch) or mod._F.get(ch.upper()) or mod._F[' ']
        for r in range(gh):
            bits = sum(1 << (gw - 1 - c) for c in range(gw) if bmp[r][c] == '1')
            rows.append(bits)
    with open("../miner/font_w_gs.h", "w") as f:
        f.write("/* generated by viz/gen_font_c.py from font5x7w - do not edit */\n")
        f.write("#ifndef FONT_W_GS_H\n#define FONT_W_GS_H\n")
        f.write("#define FW_LO %d\n#define FW_HI %d\n" % (lo, hi))
        f.write("#define FW_W %d\n#define FW_H %d\n" % (gw, gh))
        f.write("static const unsigned char FONTW[%d] = {\n" % len(rows))
        for i in range(0, len(rows), gh):
            f.write("    " + ",".join("0x%02x" % b for b in rows[i:i + gh]) + ",\n")
        f.write("};\n#endif\n")
    print("wrote miner/font_w_gs.h (%d glyphs, %dx%d)" % (hi - lo + 1, gw, gh))


if __name__ == "__main__":
    emit_main()
    emit_wallet()
